[package]
name = "jackbeer"
version = "0.1.0"
authors = ["CÃ©dric Taschereau <cedric.taschereau@boreal-is.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
